let num1=0;
let num2=0;
num1 = num1 + 3;
num2 = num2 + 7;
alert (`El primer numero ahora es ${num1} `);
alert (`El segundo numero ahora es ${num2} ` );
let a, b;
a = 3; b = 7;
resultado = a * b;
document.write(`Variable a contiene ${a} <br> ` );
document.write(`Variable b contiene ${b} <br> ` );
document.write(`El producto de a por b es ${result} <br> `);
document.write("Los puntos de interrupcion son fundamentales para programar");
